---


- name: "Check vars | Assert sb_users_definition is defined"
  assert:
    that:
      - "sb_users_definition is defined"
    msg: "sb_users_definition must be defined"
  when: sb_app_create_users

- name: "Check vars | Assert sb_user_groups_definitions is defined"
  assert:
    that:
      - "sb_user_groups_definitions is defined"
    msg: "sb_user_groups_definitions must be defined"
  when: sb_app_create_users

- name: "Check vars | Assert sb_app_name is defined"
  assert:
    that:
      - "sb_app_name is defined"
    msg: "sb_app_name must be defined"

- name: "Check vars | Assert sb_app_group_id is defined"
  assert:
    that:
      - "sb_app_group_id is defined"
    msg: "sb_app_group_id must be defined"

- name: "Check vars | Assert sb_app_artifact_id is defined"
  assert:
    that:
      - "sb_app_artifact_id is defined"
    msg: "sb_app_artifact_id must be defined"

- name: "Check vars | Assert sb_app_version is defined"
  assert:
    that:
      - "sb_app_version is defined"
    msg: "sb_app_version must be defined"

- name: "Check vars | Assert sb_app_user is defined"
  assert:
    that:
      - "sb_app_user is defined"
    msg: "sb_app_user must be defined"

- name: "Check vars | Assert sb_app_user_group is defined"
  assert:
    that:
      - "sb_app_user_group is defined"
    msg: "sb_app_user_group must be defined"

- name: "Check vars | Assert sb_maven_repository_url or sb_app_artifact_file is defined"
  assert:
    that:
      - "sb_maven_repository_url is defined or sb_app_artifact_file is defined"
    msg: "sb_maven_repository_url or sb_app_artifact_file must be defined"
